version: "3.9"

services:
  devopsdb:
    image: sreenadh45/dockerp1:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
    networks:
      - mynetwork

  application:
    image: sreenadh45/dockerp1:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
      - rabbitmq
    networks:
      - mynetwork
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # broker port
      - "15672:15672"   # management UI
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
    attachable: true
